[build]
  # Build command for the SITE app
  command = "cd apps/site && npm install && npm run build"
  
  # Directory to publish (SITE build output)
  publish = "apps/site/dist"
  
  # Base directory for build
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "22"
  
  # Build environment
  NODE_ENV = "production"

# Redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache build assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these will be set in Netlify dashboard)
# VITE_AUTH0_DOMAIN
# VITE_AUTH0_CLIENT_ID
# VITE_AUTH0_AUDIENCE
# VITE_CESIUM_ION_TOKEN
# VITE_API_BASE_URL
